### ISSUE TITLE
How to download imdb raw movies?

### ISSUE THREAD

**Issue by fake-warrior8** [waybarrios/guidance-based-video-grounding#1]
Hi, I noticed that you used the raw movie videos of the MAD dataset while the author of MAD only provided the CLIP features. I'd like to know how to download the raw movie videos of the MAD datasets?

**Comment by waybarrios** [comment]
Hi @fake-warrior8, we used the CLIP features from the original repo. However, we also added a new additional set of features, the audio ones, we are happy to release soon.
